# Generated by Django 5.1.3 on 2024-11-30 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_each',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
