# Generated by Django 5.1.3 on 2024-11-30 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_product_price_each'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
