# Generated by Django 5.1.3 on 2024-11-30 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_product_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.CharField(default='Unknown Supplier', max_length=200),
        ),
    ]
