# Generated by Django 5.1.3 on 2024-12-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.CharField(default='N/A', max_length=200),
        ),
    ]
