# Generated by Django 5.1.3 on 2024-12-21 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='threshold',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
